package com.mirage.hms.model;
// Generated 01-Mar-2020 22:54:27 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Floor generated by hbm2java
 */
@Entity
@Table(name="floor"
    ,catalog="hms"
)
public class Floor  implements java.io.Serializable {


     private int floorId;
     private Integer hotelId;
     private String desc;

    public Floor() {
    }

	
    public Floor(int floorId) {
        this.floorId = floorId;
    }
    public Floor(int floorId, Integer hotelId, String desc) {
       this.floorId = floorId;
       this.hotelId = hotelId;
       this.desc = desc;
    }
   
     @Id 

    
    @Column(name="floorId", unique=true, nullable=false)
    public int getFloorId() {
        return this.floorId;
    }
    
    public void setFloorId(int floorId) {
        this.floorId = floorId;
    }

    
    @Column(name="hotelId")
    public Integer getHotelId() {
        return this.hotelId;
    }
    
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    
    @Column(name="desc", length=45)
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }




}


