package com.mirage.hms.model;
// Generated 01-Mar-2020 22:54:27 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Hotel generated by hbm2java
 */
@Entity
@Table(name="hotel"
    ,catalog="hms"
)
public class Hotel  implements java.io.Serializable {


     private int hotelId;
     private String name;
     private String location;

    public Hotel() {
    }

	
    public Hotel(int hotelId) {
        this.hotelId = hotelId;
    }
    public Hotel(int hotelId, String name, String location) {
       this.hotelId = hotelId;
       this.name = name;
       this.location = location;
    }
   
     @Id 

    
    @Column(name="hotelId", unique=true, nullable=false)
    public int getHotelId() {
        return this.hotelId;
    }
    
    public void setHotelId(int hotelId) {
        this.hotelId = hotelId;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="location", length=45)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }




}


