package com.mirage.hms.model;
// Generated 01-Mar-2020 22:54:27 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Method generated by hbm2java
 */
@Entity
@Table(name="method"
    ,catalog="hms"
)
public class Method  implements java.io.Serializable {


     private int methodId;
     private String name;
     private String desc;

    public Method() {
    }

	
    public Method(int methodId) {
        this.methodId = methodId;
    }
    public Method(int methodId, String name, String desc) {
       this.methodId = methodId;
       this.name = name;
       this.desc = desc;
    }
   
     @Id 

    
    @Column(name="methodId", unique=true, nullable=false)
    public int getMethodId() {
        return this.methodId;
    }
    
    public void setMethodId(int methodId) {
        this.methodId = methodId;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="desc", length=45)
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }




}


