package com.mirage.hms.model;
// Generated 01-Mar-2020 22:54:27 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name="payment"
    ,catalog="hms"
)
public class Payment  implements java.io.Serializable {


     private int paymentId;
     private Integer customerId;
     private Integer bookingId;
     private Double amount;
     private Date date;

    public Payment() {
    }

	
    public Payment(int paymentId) {
        this.paymentId = paymentId;
    }
    public Payment(int paymentId, Integer customerId, Integer bookingId, Double amount, Date date) {
       this.paymentId = paymentId;
       this.customerId = customerId;
       this.bookingId = bookingId;
       this.amount = amount;
       this.date = date;
    }
   
     @Id 

    
    @Column(name="paymentId", unique=true, nullable=false)
    public int getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(int paymentId) {
        this.paymentId = paymentId;
    }

    
    @Column(name="customerId")
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="bookingId")
    public Integer getBookingId() {
        return this.bookingId;
    }
    
    public void setBookingId(Integer bookingId) {
        this.bookingId = bookingId;
    }

    
    @Column(name="amount", precision=22, scale=0)
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


