package com.mirage.hms.model;
// Generated 01-Mar-2020 22:54:27 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Room generated by hbm2java
 */
@Entity
@Table(name="room"
    ,catalog="hms"
)
public class Room  implements java.io.Serializable {


     private int roomId;
     private Integer roomtypeId;
     private Integer floorId;
     private Integer capacity;
     private String size;
     private Double rent;
     private String desc;

    public Room() {
    }

	
    public Room(int roomId) {
        this.roomId = roomId;
    }
    public Room(int roomId, Integer roomtypeId, Integer floorId, Integer capacity, String size, Double rent, String desc) {
       this.roomId = roomId;
       this.roomtypeId = roomtypeId;
       this.floorId = floorId;
       this.capacity = capacity;
       this.size = size;
       this.rent = rent;
       this.desc = desc;
    }
   
     @Id 

    
    @Column(name="roomId", unique=true, nullable=false)
    public int getRoomId() {
        return this.roomId;
    }
    
    public void setRoomId(int roomId) {
        this.roomId = roomId;
    }

    
    @Column(name="roomtypeId")
    public Integer getRoomtypeId() {
        return this.roomtypeId;
    }
    
    public void setRoomtypeId(Integer roomtypeId) {
        this.roomtypeId = roomtypeId;
    }

    
    @Column(name="floorId")
    public Integer getFloorId() {
        return this.floorId;
    }
    
    public void setFloorId(Integer floorId) {
        this.floorId = floorId;
    }

    
    @Column(name="capacity")
    public Integer getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

    
    @Column(name="size", length=45)
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }

    
    @Column(name="rent", precision=22, scale=0)
    public Double getRent() {
        return this.rent;
    }
    
    public void setRent(Double rent) {
        this.rent = rent;
    }

    
    @Column(name="desc", length=45)
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }




}


