package com.mirage.hms.model;
// Generated 01-Mar-2020 22:54:27 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Roomtype generated by hbm2java
 */
@Entity
@Table(name="roomtype"
    ,catalog="hms"
)
public class Roomtype  implements java.io.Serializable {


     private int roomtypeId;
     private String desc;

    public Roomtype() {
    }

	
    public Roomtype(int roomtypeId) {
        this.roomtypeId = roomtypeId;
    }
    public Roomtype(int roomtypeId, String desc) {
       this.roomtypeId = roomtypeId;
       this.desc = desc;
    }
   
     @Id 

    
    @Column(name="roomtypeId", unique=true, nullable=false)
    public int getRoomtypeId() {
        return this.roomtypeId;
    }
    
    public void setRoomtypeId(int roomtypeId) {
        this.roomtypeId = roomtypeId;
    }

    
    @Column(name="desc", length=45)
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }




}


